#!/usr/bin/env bash
set -euo pipefail

: "${BACKEND:=backend:8000}"
: "${SOCKETIO:=websocket:9000}"
: "${FRAPPE_SITE_NAME_HEADER:=\$host}"
: "${UPSTREAM_REAL_IP_ADDRESS:=127.0.0.1}"
: "${UPSTREAM_REAL_IP_HEADER:=X-Forwarded-For}"
: "${UPSTREAM_REAL_IP_RECURSIVE:=off}"
: "${PROXY_READ_TIMEOUT:=120s}"
: "${CLIENT_MAX_BODY_SIZE:=2g}"

export BACKEND SOCKETIO FRAPPE_SITE_NAME_HEADER UPSTREAM_REAL_IP_ADDRESS
export UPSTREAM_REAL_IP_HEADER UPSTREAM_REAL_IP_RECURSIVE PROXY_READ_TIMEOUT CLIENT_MAX_BODY_SIZE

envsubst '${BACKEND} ${SOCKETIO} ${FRAPPE_SITE_NAME_HEADER} ${UPSTREAM_REAL_IP_ADDRESS} ${UPSTREAM_REAL_IP_HEADER} ${UPSTREAM_REAL_IP_RECURSIVE} ${PROXY_READ_TIMEOUT} ${CLIENT_MAX_BODY_SIZE}' \
	< /templates/nginx/frappe.conf.template \
	> /etc/nginx/conf.d/frappe.conf

exec nginx -g 'daemon off;'
