dbfilename redis_queue.rdb
dir /Users/anthonywaichungo/Documents/Projects/Personal/UN/lms/frappe-bench/config/pids
pidfile /Users/anthonywaichungo/Documents/Projects/Personal/UN/lms/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/anthonywaichungo/Documents/Projects/Personal/UN/lms/frappe-bench/config/redis_queue.acl
