# Copyright (c) 2026, FOSS United and contributors
# For license information, please see license.txt

import os
import shutil

import frappe
from frappe.model.document import Document

from lms.lms.video import paths


class LMSVideo(Document):
	def before_insert(self):
		if not self.video_id:
			self.video_id = paths.new_video_id()

	def on_trash(self):
		"""Drop the packaged folder along with the doc.

		The folder is derived from `video_id`, which is validated hex and was
		generated by us — but rmtree is destructive enough to re-check
		containment under the site's files dir before running it.
		"""
		for is_private in (True, False):
			try:
				folder = paths.video_dir(self.video_id, is_private=is_private)
			except Exception:
				continue
			_rmtree_if_inside_site(folder)

		_rmtree_if_inside_site(paths.tmp_dir(self.video_id))

	def set_status(self, status: str, error: str | None = None, commit: bool = True):
		"""Move the doc to `status` and tell any open editor about it.

		Uses db_set rather than db.set_value: the latter bumps `modified` in the
		database while leaving this in-memory document stale, so the final
		`doc.save()` at the end of packaging would fail its concurrency check
		against writes this same job had made.
		"""
		self.db_set("status", status, update_modified=True, commit=commit)
		if error is not None:
			self.db_set("error_log", error, update_modified=True, commit=commit)

		publish_video_status(self)


def publish_video_status(doc: "LMSVideo"):
	from frappe.realtime import get_website_room

	frappe.publish_realtime(
		event="lms_video_status",
		room=get_website_room(),
		message={
			"video_id": doc.video_id,
			"status": doc.status,
			"manifest_url": doc.manifest_url,
			"poster_url": doc.poster_url,
			"duration": doc.duration,
			"error": doc.error_log,
		},
		after_commit=True,
	)


def _rmtree_if_inside_site(folder: str):
	site_files = os.path.realpath(frappe.get_site_path())
	target = os.path.realpath(folder)

	if not target.startswith(site_files + os.sep):
		frappe.logger("lms").warning(f"Refusing to delete video folder outside the site: {target}")
		return

	shutil.rmtree(target, ignore_errors=True)
